Controllers/EmployerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HouseHelp.Data;
using HouseHelp.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace HouseHelp.Controllers
{
    [Authorize]
    public class EmployerController : Controller
    {
        private readonly ApplicationDbContext _context;
        private UserManager<ApplicationUser> _userManager;

        public EmployerController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Employer
        [Authorize(Roles = ("Admin"))]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Employer.ToListAsync());
        }

        // GET: Employer/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employerModel = await _context.Employer
                .SingleOrDefaultAsync(m => m.EmployerId == id);
            if (employerModel == null)
            {
                return NotFound();
            }

            return View(employerModel);
        }

        // GET: Employer/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Employer/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = (""+AppUtils.AppRoles.EMPLOYER + "," + AppUtils.AppRoles.ADMIN+""))]
        public async Task<IActionResult> Create([Bind("EmployerId,Surname,Firstname,Lastname,Gender,Religion,Occupation," +
            "Address,State,Phone,Email,CreatedAt,UpdatedAt")] EmployerModel employerModel)
        {
            if (ModelState.IsValid)
            {
                var userEmail = _userManager.GetUserName(User).ToLower();
                employerModel.Email = userEmail;
                _context.Add(employerModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(HomeController.Index),"Home");
            }
            return View(employerModel);
        }

        // GET: Employer/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var employerModel = await _context.Employer.SingleOrDefaultAsync(m => m.EmployerId == id);
            if (employerModel == null)
            {
                return NotFound();
            }
            return View(employerModel);
        }

        // POST: Employer/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = ("" + AppUtils.AppRoles.EMPLOYER + "," + AppUtils.AppRoles.ADMIN + ""))]
        public async Task<IActionResult> Edit(int id, [Bind("EmployerId,Surname,Firstname,Lastname,Gender,Religion,Occupation," +
            "Address,State,Phone,Email,CreatedAt,UpdatedAt")] EmployerModel employerModel)
        {
            if (id != employerModel.EmployerId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    employerModel.Email = _userManager.GetUserName(User);
                    _context.Update(employerModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmployerModelExists(employerModel.EmployerId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }
            return View(employerModel);
        }

        // GET: Employer/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employerModel = await _context.Employer
                .SingleOrDefaultAsync(m => m.EmployerId == id);
            if (employerModel == null)
            {
                return NotFound();
            }

            return View(employerModel);
        }

        // POST: Employer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var employerModel = await _context.Employer.SingleOrDefaultAsync(m => m.EmployerId == id);
            _context.Employer.Remove(employerModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmployerModelExists(int id)
        {
            return _context.Employer.Any(e => e.EmployerId == id);
        }
    }
}

Controllers/GuarantorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HouseHelp.Data;
using HouseHelp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace HouseHelp.Controllers
{
    [Authorize]
    public class GuarantorController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public GuarantorController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Guarantor
        [Authorize(Roles ="Admin")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Guarantor.ToListAsync());
        }

        // GET: Guarantor/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var guarantorModel = await _context.Guarantor
                .SingleOrDefaultAsync(m => m.GuarantorId == id);
            if (guarantorModel == null)
            {
                return NotFound();
            }

            return View(guarantorModel);
        }

        // GET: Guarantor/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Guarantor/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GuarantorId,Surname,Firstname,Lastname,Gender,Religion,Address,State,LGA,Phone,Email,CreatedAt,UpdatedAt")] GuarantorModel guarantorModel)
        {
            if (ModelState.IsValid)
            {
                guarantorModel.Email = _userManager.GetUserId(User);
                _context.Add(guarantorModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }
            return View(guarantorModel);
        }

        // GET: Guarantor/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var guarantorModel = await _context.Guarantor.SingleOrDefaultAsync(m => m.GuarantorId == id);
            if (guarantorModel == null)
            {
                return NotFound();
            }
            return View(guarantorModel);
        }

        // POST: Guarantor/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("GuarantorId,Surname,Firstname,Lastname,Gender,Religion,Address,State,LGA,Phone,Email,CreatedAt,UpdatedAt")] GuarantorModel guarantorModel)
        {
            if (id != guarantorModel.GuarantorId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    guarantorModel.Email = _userManager.GetUserName(User);
                    guarantorModel.UpdatedAt = DateTime.Now;
                    _context.Update(guarantorModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GuarantorModelExists(guarantorModel.GuarantorId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }
            return View(guarantorModel);
        }

        // GET: Guarantor/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var guarantorModel = await _context.Guarantor
                .SingleOrDefaultAsync(m => m.GuarantorId == id);
            if (guarantorModel == null)
            {
                return NotFound();
            }

            return View(guarantorModel);
        }

        // POST: Guarantor/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var guarantorModel = await _context.Guarantor.SingleOrDefaultAsync(m => m.GuarantorId == id);
            _context.Guarantor.Remove(guarantorModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GuarantorModelExists(int id)
        {
            return _context.Guarantor.Any(e => e.GuarantorId == id);
        }
    }
}

Controllers/HelperController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HouseHelp.Data;
using HouseHelp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace HouseHelp.Controllers
{
    [Authorize]
    public class HelperController : Controller
    {
        private readonly ApplicationDbContext _context;
        private UserManager<ApplicationUser> _userManager;

        public HelperController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Helper
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var userId = _userManager.GetUserId(User);
            var value = await _context.Helper.Where(c => c.ProviderId.Equals(userId)).ToListAsync();

            if (User.IsInRole(AppUtils.AppRoles.ADMIN)) return View(await _context.Helper.ToListAsync());

            return View(await _context.Helper.Where(c => c.ProviderId.Equals(userId)).ToListAsync());
        }

        // GET: Helper/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            {
            if (id == null)
                return NotFound();
            }

            var helperModel = await _context.Helper
                .SingleOrDefaultAsync(m => m.HelperId == id);
            if (helperModel == null)
            {
                return NotFound();
            }

            return View(helperModel);
        }

        public async Task<IActionResult> AddToList(int? id)
        {
            {
                if (id == null)
                    return NotFound();
            }

            var helperModel = await _context.Helper
                .SingleOrDefaultAsync(m => m.HelperId == id);
            if (helperModel == null)
            {
                return NotFound();
            }

            //var changeStatus = new HelperModel() { };
            helperModel.Status = AppUtils.HelperStatusEnum.Held;
            helperModel.Employer = _userManager.GetUserId(User);
            _context.Entry(helperModel).State = EntityState.Modified;
            _context.SaveChanges();
            
           

            return RedirectToAction("Index");
        }

        // GET: Helper/Create
        public IActionResult Create()
        {
            return View();
        }

        public async Task<IActionResult> Checklist()
        {
            string userId = _userManager.GetUserId(User);

            return View(await _context.Helper.Where(c => c.Employer.Equals(userId)).ToListAsync());
        }

        // POST: Helper/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles =("Admin, Guarantor"))]
        public async Task<IActionResult> Create([Bind("HelperId,Surname,Firstname,Lastname,Gender,State,Religion," +
            "Qualification,Language,DateOfBirth,NextOfKinName,NextOfKinAddress,NextOfKinPhone,ProviderId,CreatedAt,UpdatedAt")] HelperModel helperModel)
        {
            if (ModelState.IsValid)
            {
                var userId = _userManager.GetUserId(User);
                helperModel.ProviderId = userId;
                _context.Add(helperModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(helperModel);
        }

        // GET: Helper/Edit/5
        [Authorize(Roles = "Admin,Guarantor")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var helperModel = await _context.Helper.SingleOrDefaultAsync(m => m.HelperId == id);
            if (helperModel == null)
            {
                return NotFound();
            }
            return View(helperModel);
        }

        // POST: Helper/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Guarantor")]
        public async Task<IActionResult> Edit(int id, [Bind("HelperId,Surname,Firstname,Lastname,Gender,State,Religion,Qualification," +
            "Language,Status,DateOfBirth,NextOfKinName,NextOfKinAddress,NextOfKinPhone,ProviderId,CreatedAt,UpdatedAt")] HelperModel helperModel)
        {
            if (id != helperModel.HelperId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(helperModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HelperModelExists(helperModel.HelperId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(helperModel);
        }

        // GET: Helper/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var helperModel = await _context.Helper
                .SingleOrDefaultAsync(m => m.HelperId == id);
            if (helperModel == null)
            {
                return NotFound();
            }

            return View(helperModel);
        }

        // POST: Helper/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles ="Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var helperModel = await _context.Helper.SingleOrDefaultAsync(m => m.HelperId == id);
            _context.Helper.Remove(helperModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HelperModelExists(int id)
        {
            return _context.Helper.Any(e => e.HelperId == id);
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using HouseHelp.AppUtils
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HouseHelp App</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">HH App</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    @if (!SignInManager.IsSignedIn(User))
                    {
                        <li><a asp-area="" asp-controller="Guarantor" asp-action="Create">Become a Provider</a></li>
                    }

                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>

                    @if (User.IsInRole(AppRoles.EMPLOYER))
                    {
                        <li><a asp-area="" asp-controller="Employer" asp-action="Edit" asp-route-id="@ViewData["EmployerId"]">Update Profile</a></li>
                        <li><a asp-area="" asp-controller="Helper" asp-action="Checklist">Checklist</a></li>
                    }

                    @if (User.IsInRole(HouseHelp.AppUtils.AppRoles.GUARANTOR))
                    {
                        <li><a asp-area="" asp-controller="Guarantor" asp-action="Edit" asp-route-id="@ViewData["GuarantorId"]">Update Profile</a></li>
                        <li><a asp-area="" asp-controller="Helper" asp-action="Create">Register Helper</a></li>
                        <li><a asp-area="" asp-controller="Guarantor" asp-action="ViewHelpers">View Employers</a></li>
                    }

                     @if (User.IsInRole(HouseHelp.AppUtils.AppRoles.ADMIN))
                     { 
                        <li><a asp-area="" asp-controller="Guarantor" asp-action="Index">Guarantors</a></li>
                        <li><a asp-area="" asp-controller="Employer" asp-action="Index">Employers</a></li>
                        <li><a asp-area="" asp-controller="Helper" asp-action="Index">Helpers</a></li>
                     }

                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - HouseHelp</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>